# Site
name: 'Furkan Cankaya'
description: 'Furkan Cankaya Blok'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog'
disqus: 'furkancankaya'
email: 'furkancankayaaa@gmail.com'
mailchimp-list: '-'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    furkan:
      name:           Furkan Cankaya
      site:           furkan.cankaya.io
      avatar:         /assets/images/furkan.jpg
      bio:            "Hi, I am Furkan, the author of this blog. I hope you like it!"
      email:          furkancankayaaa@gmail.com
      twitter:        https://twitter.com/furkancnyk
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: furkan
      avatar: /assets/images/furkan.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]